from .branch_officces import BranchOfficeModelSerializer
from .job_applications import RetrieveJobApplitacionModelSerializer, JobApplitacionModelSerializer
from .advertising_compaigns import AdvertisingCampaignModelSerializer


