# Generated by Django 4.1.3 on 2022-12-02 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_jobapplitacion_branch_office'),
        ('users', '0007_clientprofile_branch_office_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='branch_office_default',
        ),
        migrations.AddField(
            model_name='user',
            name='branch_office_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.branchoffice'),
        ),
    ]
