# Generated by Django 4.1.3 on 2022-12-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_clientprofile_branch_office_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='contract_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('ADM', 'administrator'), ('CL', 'cliente')], default='CL', max_length=3),
        ),
    ]
