# Generated by Django 4.1.4 on 2022-12-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_clientprofile_contract_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_enterprise',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='ClientProfile',
        ),
    ]
