# Generated by Django 4.1.3 on 2022-12-02 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingCampaign',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.IntegerField()),
                ('interactions', models.IntegerField()),
                ('result', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BranchOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name_branch', models.CharField(max_length=500)),
                ('commercial_business', models.TextField(max_length=1200)),
                ('dni_branch', models.CharField(max_length=15)),
                ('owner_adm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobApplitacion',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budget', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=1200)),
                ('start_date', models.DateField()),
                ('end_data', models.DateField()),
                ('report_adm', models.TextField(blank=True, max_length=1200, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_answer', models.BooleanField(default=False)),
                ('owner_adm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_adm_user', to=settings.AUTH_USER_MODEL)),
                ('owner_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_client_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='College',
        ),
        migrations.AddField(
            model_name='advertisingcampaign',
            name='job_applitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.jobapplitacion'),
        ),
    ]
