# Generated by Django 4.1.3 on 2022-12-02 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_advertisingcampaign_branchoffice_jobapplitacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchoffice',
            name='owner_adm',
        ),
    ]
