# Generated by Django 4.1.3 on 2022-12-03 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_branchoffice_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisingcampaign',
            name='branch_office',
        ),
    ]
