# Generated by Django 4.1.3 on 2022-12-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_remove_advertisingcampaign_branch_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisingcampaign',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
