# Generated by Django 4.1.4 on 2022-12-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_advertisingcampaign_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisingcampaign',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='advertisingcampaign',
            name='frequency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisingcampaign',
            name='interactions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisingcampaign',
            name='result',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisingcampaign',
            name='scope',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
