# Generated by Django 4.1.4 on 2022-12-19 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0010_advertisingcampaign_facebook_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplitacion',
            name='owner_adm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_adm_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
