# Generated by Django 4.1.4 on 2022-12-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0011_alter_jobapplitacion_owner_adm'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplitacion',
            name='image_grafic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='jobapplitacion',
            name='is_confirmgrafic',
            field=models.BooleanField(default=False),
        ),
    ]
