# Generated by Django 4.1.4 on 2022-12-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0012_jobapplitacion_image_grafic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplitacion',
            name='payment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
