# Generated by Django 4.1.4 on 2022-12-20 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0016_advertisingcampaign_img_chart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisingcampaign',
            old_name='interactions',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='advertisingcampaign',
            name='frequency',
        ),
    ]
